# Generated by Django 5.2.7 on 2025-11-13 07:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='notificationgenerator',
            name='channel',
            field=models.CharField(choices=[('sms', 'SMS'), ('email', 'Email'), ('telegram', 'Telegram')], default='telegram', max_length=20),
        ),
        migrations.AddField(
            model_name='notificationgenerator',
            name='notifications_amount',
            field=models.IntegerField(default=0),
        ),
    ]
