# Generated by Django 5.2.7 on 2025-11-13 13:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0002_notificationgenerator_channel_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='notificationgenerator',
            name='notifications_amount',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
