# Generated by Django 5.2.7 on 2025-11-13 13:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0003_alter_notificationgenerator_notifications_amount'),
    ]

    operations = [
        migrations.RenameField(
            model_name='notificationgenerator',
            old_name='channel',
            new_name='initial_channel',
        ),
    ]
