# Generated by Django 5.2.7 on 2025-11-13 16:48

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0004_rename_channel_notificationgenerator_initial_channel'),
    ]

    operations = [
        migrations.AlterField(
            model_name='notificationgenerator',
            name='notifications_amount',
            field=models.PositiveIntegerField(default=1, validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(100)]),
        ),
    ]
