# Generated by Django 5.2.7 on 2025-11-13 17:53

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0005_alter_notificationgenerator_notifications_amount'),
    ]

    operations = [
        migrations.AlterField(
            model_name='notificationgenerator',
            name='notifications_amount',
            field=models.PositiveIntegerField(default=0, validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(10000)]),
        ),
    ]
