# Generated by Django 5.2.7 on 2025-11-13 07:15

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('up', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='notification',
            name='priority',
        ),
        migrations.CreateModel(
            name='NotificationRecipient',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('channel', models.CharField(choices=[('sms', 'SMS'), ('email', 'Email'), ('telegram', 'Telegram')], max_length=20)),
                ('recipient_address', models.CharField(max_length=255)),
                ('sent_at', models.DateTimeField(blank=True, null=True)),
                ('delivered_at', models.DateTimeField(blank=True, null=True)),
                ('error_message', models.TextField(blank=True, null=True)),
                ('retry_count', models.IntegerField(default=0)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('sent', 'Sent'), ('failed', 'Failed')], default='pending', max_length=20)),
                ('notification', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='up.notification')),
            ],
            options={
                'db_table': 'notification_recipient',
            },
        ),
        migrations.CreateModel(
            name='NotificationEvent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('action', models.CharField(choices=[('sent', 'Sent'), ('failed', 'Failed'), ('retried', 'Retried'), ('delivered', 'Delivered')], max_length=20)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('sent', 'Sent'), ('failed', 'Failed')], default='pending', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('recipient', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='events', to='up.notificationrecipient')),
            ],
            options={
                'db_table': 'notification_event',
            },
        ),
    ]
