# Generated by Django 5.2.7 on 2025-11-13 15:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('up', '0002_remove_notification_priority_notificationrecipient_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='notificationrecipient',
            name='notification',
        ),
        migrations.RemoveField(
            model_name='notification',
            name='scheduled_at',
        ),
        migrations.AddField(
            model_name='notification',
            name='channel',
            field=models.CharField(choices=[('sms', 'SMS'), ('email', 'Email'), ('telegram', 'Telegram')], default='email', max_length=20),
        ),
        migrations.DeleteModel(
            name='NotificationEvent',
        ),
        migrations.DeleteModel(
            name='NotificationRecipient',
        ),
    ]
