# Generated by Django 5.2.7 on 2025-11-13 16:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('up', '0003_remove_notificationrecipient_notification_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='notification',
            name='retry_num',
            field=models.PositiveSmallIntegerField(default=0),
        ),
    ]
