# Generated by Django 5.2.7 on 2025-11-13 16:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('up', '0004_notification_retry_num'),
    ]

    operations = [
        migrations.RenameField(
            model_name='notification',
            old_name='channel',
            new_name='initial_channel',
        ),
        migrations.AddField(
            model_name='notification',
            name='actual_channel',
            field=models.CharField(blank=True, choices=[('sms', 'SMS'), ('email', 'Email'), ('telegram', 'Telegram')], max_length=20, null=True),
        ),
    ]
